"""
Response models for the Lunar Solar Simulator API.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class TimeSeriesPoint(BaseModel):
    """Single data point in the simulation time series."""
    time_hour: int = Field(..., description="Hour of simulation")
    energy_generated_gw: float = Field(..., description="Energy generated in GW")
    energy_received_gw: float = Field(..., description="Energy received on Earth in GW")
    solar_exposure: Optional[float] = Field(
        default=None, 
        description="Solar exposure factor (0-1) if lunar cycle enabled"
    )
    atmospheric_loss: Optional[float] = Field(
        default=None,
        description="Atmospheric loss percentage if enabled"
    )


class GroundStationOutput(BaseModel):
    """Energy distribution data for a single ground station."""
    station_id: int = Field(..., description="Unique station identifier")
    received_gw: float = Field(..., description="Energy received at this station in GW")
    latitude: Optional[float] = Field(default=None, description="Station latitude")
    longitude: Optional[float] = Field(default=None, description="Station longitude")
    name: Optional[str] = Field(default=None, description="Station name")


class OptimizationResult(BaseModel):
    """Results from parameter optimization."""
    optimal_ring_width_km: float
    optimal_efficiency: float
    optimal_stations: int
    optimal_transmission_type: str
    predicted_energy_gw: float
    improvement_percent: float


class SimulationResponse(BaseModel):
    """Complete simulation response with all computed results."""
    total_energy_generated_gw: float = Field(
        ..., 
        description="Total energy generated by lunar ring in GW"
    )
    energy_received_gw: float = Field(
        ..., 
        description="Energy received on Earth after transmission in GW"
    )
    transmission_loss_percent: float = Field(
        ..., 
        description="Percentage of energy lost during transmission"
    )
    system_efficiency: float = Field(
        ..., 
        description="Overall system efficiency (0-1)"
    )
    stations: List[GroundStationOutput] = Field(
        ..., 
        description="Energy distribution per ground station"
    )
    time_series: List[TimeSeriesPoint] = Field(
        ..., 
        description="Hourly simulation data"
    )
    insights: List[str] = Field(
        ..., 
        description="AI-generated insights and recommendations"
    )
    optimization: Optional[OptimizationResult] = Field(
        default=None,
        description="Optimization results if requested"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "total_energy_generated_gw": 1234.56,
                    "energy_received_gw": 987.65,
                    "transmission_loss_percent": 20.0,
                    "system_efficiency": 0.80,
                    "stations": [
                        {"station_id": 1, "received_gw": 197.53}
                    ],
                    "time_series": [
                        {"time_hour": 0, "energy_generated_gw": 1234.56, "energy_received_gw": 987.65}
                    ],
                    "insights": ["System is highly efficient"]
                }
            ]
        }
    }


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(..., description="Service status")
    version: str = Field(..., description="API version")
    simulation_ready: bool = Field(..., description="Whether simulation service is ready")


class ScenarioComparison(BaseModel):
    """Comparison between multiple simulation scenarios."""
    scenario_id: str
    name: str
    params: dict
    results: SimulationResponse
    

class ExportFormat(BaseModel):
    """Export configuration."""
    format: str = Field(..., description="Export format: pdf, csv, json")
    include_graphs: bool = Field(default=True)
    include_insights: bool = Field(default=True)