"""
Energy Generation Model for Lunar Solar Simulator
Calculates energy output from the lunar solar ring with optional advanced physics.
"""
import math
from typing import Optional
from utils.constants import (
    SOLAR_CONSTANT, 
    MOON_RADIUS_KM, 
    PANEL_DEGRADATION,
    WATTS_TO_GW,
    KM2_TO_M2,
)


def calculate_energy(
    ring_width_km: float, 
    efficiency: float,
    include_lunar_cycle: bool = False,
    lunar_day_hour: float = 354.0,
    years_in_operation: float = 0.0,
) -> float:
    """
    Calculate total energy generated by the lunar solar ring.
    
    The lunar ring is a band of solar panels around the Moon's equator.
    Energy generation depends on:
    - Ring dimensions (width determines total panel area)
    - Panel efficiency (conversion of sunlight to electricity)
    - Solar exposure (affected by lunar day/night cycle)
    - Panel degradation (aging effects)
    
    Args:
        ring_width_km: Width of the solar panel ring in kilometers
        efficiency: Solar panel efficiency (0.0 to 1.0)
        include_lunar_cycle: Whether to include lunar day/night effects
        lunar_day_hour: Current hour in lunar day (0-708)
        years_in_operation: Years since installation (for degradation)
        
    Returns:
        Total energy generated in gigawatts (GW)
    """
    # Calculate ring area
    circumference_km = 2 * math.pi * MOON_RADIUS_KM
    area_km2 = circumference_km * ring_width_km
    area_m2 = area_km2 * KM2_TO_M2
    
    # Base energy calculation
    energy_watts = area_m2 * SOLAR_CONSTANT * efficiency
    
    # Apply panel degradation
    degradation_factor = PANEL_DEGRADATION
    if years_in_operation > 0:
        from services.physics_model import calculate_panel_degradation
        degradation_factor *= calculate_panel_degradation(years_in_operation)
    
    energy_watts *= degradation_factor
    
    # Apply lunar cycle effects if enabled
    if include_lunar_cycle:
        from services.physics_model import calculate_ring_average_exposure
        exposure = calculate_ring_average_exposure(ring_width_km)
        energy_watts *= exposure
    
    # Convert to gigawatts
    return energy_watts * WATTS_TO_GW


def calculate_energy_with_physics(
    ring_width_km: float,
    efficiency: float,
    lunar_day_hour: float = 354.0,
    years_in_operation: float = 0.0,
    solar_intensity_factor: float = 1.0,
) -> dict:
    """
    Calculate energy with detailed physics breakdown.
    
    Returns a dictionary with energy values and all contributing factors.
    
    Args:
        ring_width_km: Width of the solar panel ring in kilometers
        efficiency: Base solar panel efficiency (0.0 to 1.0)
        lunar_day_hour: Current hour in lunar day (0-708)
        years_in_operation: Years since installation
        solar_intensity_factor: Solar intensity multiplier
        
    Returns:
        Dictionary containing:
        - total_energy_gw: Final energy output
        - base_energy_gw: Energy before adjustments
        - effective_efficiency: Efficiency after temperature effects
        - degradation_factor: Panel degradation multiplier
        - exposure_factor: Solar exposure multiplier
        - breakdown: Detailed calculation breakdown
    """
    from services.physics_model import (
        calculate_ring_average_exposure,
        calculate_panel_degradation,
        calculate_panel_temperature_efficiency,
    )
    
    # Calculate ring area
    circumference_km = 2 * math.pi * MOON_RADIUS_KM
    area_km2 = circumference_km * ring_width_km
    area_m2 = area_km2 * KM2_TO_M2
    
    # Base energy (ideal conditions)
    base_energy_watts = area_m2 * SOLAR_CONSTANT * efficiency
    base_energy_gw = base_energy_watts * WATTS_TO_GW
    
    # Temperature-adjusted efficiency
    effective_efficiency = calculate_panel_temperature_efficiency(
        solar_intensity_factor, 
        efficiency
    )
    
    # Degradation factor
    degradation_factor = PANEL_DEGRADATION * calculate_panel_degradation(years_in_operation)
    
    # Solar exposure (ring average)
    exposure_factor = calculate_ring_average_exposure(ring_width_km)
    
    # Final energy calculation
    total_energy_watts = (
        area_m2 
        * SOLAR_CONSTANT 
        * effective_efficiency 
        * degradation_factor 
        * exposure_factor
        * solar_intensity_factor
    )
    total_energy_gw = total_energy_watts * WATTS_TO_GW
    
    return {
        "total_energy_gw": total_energy_gw,
        "base_energy_gw": base_energy_gw,
        "effective_efficiency": effective_efficiency,
        "degradation_factor": degradation_factor,
        "exposure_factor": exposure_factor,
        "breakdown": {
            "ring_area_km2": area_km2,
            "ring_area_m2": area_m2,
            "circumference_km": circumference_km,
            "solar_constant_w_m2": SOLAR_CONSTANT,
            "base_efficiency": efficiency,
            "temperature_adjusted_efficiency": effective_efficiency,
            "years_degradation": years_in_operation,
        }
    }
